spring.application.name=call-monitoring
# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/call_monitoring
spring.datasource.username=root
spring.datasource.password=your_password

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# WebSocket
server.port=8080
